import { FormEvent, useEffect, useState } from 'react'

type User = { email: string; role: string }
type Submission = { submission_number: string; submission_type: string; submission_status: string; insured_firstname: string; insured_lastname: string; insured_age: number; insured_code: number; insured_email_address: string; insured_address_1?: string; insured_city?: string; submission_summary?: string }
type Analysis = { risk_summary: string; recommendation: string; risk_level: string; risk_score: number; risk_factors: string; missing_information?: string }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:5000'

async function request<T>(path: string, token?: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } })
  if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.detail ?? 'Something went wrong.') }
  return response.json()
}

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('insurance-token') ?? '')
  const [user, setUser] = useState<User | null>(JSON.parse(localStorage.getItem('insurance-user') ?? 'null'))
  const [tab, setTab] = useState<'overview' | 'new'>('overview')
  const [submissions, setSubmissions] = useState<Submission[]>([])
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const load = async () => { if (!token) return; try { setSubmissions(await request<Submission[]>('/search', token)); } catch (e) { setError((e as Error).message) } }
  useEffect(() => { load() }, [token])
  const signOut = () => { localStorage.clear(); setToken(''); setUser(null); setSubmissions([]); setAnalysis(null) }
  if (!token || !user) return <Auth onLogin={(nextToken, nextUser) => { localStorage.setItem('insurance-token', nextToken); localStorage.setItem('insurance-user', JSON.stringify(nextUser)); setToken(nextToken); setUser(nextUser) }} />
  const underwriter = user.role.toUpperCase() === 'UNDERWRITER'
  const updateStatus = async (number: string, status: string) => { setBusy(true); setError(''); try { await request(`/update/${number}`, token, { method: 'PATCH', body: JSON.stringify({ submission_status: status }) }); await load() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const viewAnalysis = async (number: string) => { setBusy(true); setError(''); try { setAnalysis((await request<Analysis[]>(`/analysis/${number}`, token))[0]) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <main className="app"><aside><div className="brand"><span>✦</span> SignalUnderwrite</div><p className="role">{user.role}</p><nav><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>▦ Overview</button><button className={tab === 'new' ? 'active' : ''} onClick={() => setTab('new')}>＋ New submission</button></nav><div className="profile"><div className="avatar">{user.email[0].toUpperCase()}</div><span>{user.email}</span><button onClick={signOut}>Sign out</button></div></aside><section className="content"><header><div><p className="eyebrow">UNDERWRITING WORKSPACE</p><h1>{tab === 'overview' ? 'Submission dashboard' : 'Create a submission'}</h1></div><button className="refresh" onClick={load}>↻ Refresh</button></header>{error && <div className="notice">{error}<button onClick={() => setError('')}>×</button></div>}{tab === 'new' ? <SubmissionForm token={token} onCreated={() => { setTab('overview'); load() }} /> : <><div className="metrics"><Metric title="Total submissions" value={submissions.length} /><Metric title="Pending review" value={submissions.filter(s => s.submission_status === 'SUBMITTED').length} /><Metric title="Approved" value={submissions.filter(s => s.submission_status === 'APPROVED').length} /></div><div className="panel"><div className="panel-title"><h2>Submissions</h2><span>{submissions.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Reference</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody>{submissions.map(s => <tr key={s.submission_number}><td><strong>{s.insured_firstname} {s.insured_lastname}</strong><small>{s.insured_email_address} · Age {s.insured_age}</small></td><td className="mono">{s.submission_number}</td><td>{s.submission_type}</td><td><span className={`status ${s.submission_status.toLowerCase()}`}>{s.submission_status.replace('_', ' ')}</span></td><td className="actions">{underwriter && <><button onClick={() => viewAnalysis(s.submission_number)}>Analysis</button><select disabled={busy} defaultValue="" onChange={e => e.target.value && updateStatus(s.submission_number, e.target.value)}><option value="" disabled>Update status</option><option>APPROVED</option><option>REJECTED</option><option>MANUAL_REVIEW</option><option>PENDING_INFO</option></select></>}</td></tr>)}{!submissions.length && <tr><td colSpan={5} className="empty">No submissions yet.</td></tr>}</tbody></table></div></div></>}{analysis && <AnalysisModal analysis={analysis} onClose={() => setAnalysis(null)} />}</section></main>
}

function Auth({ onLogin }: { onLogin: (token: string, user: User) => void }) { const [register, setRegister] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('BROKER'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { if (register) await request('/register', undefined, { method: 'POST', body: JSON.stringify({ email, password_hash: password, role }) }); const result = await request<{ access_token: string; role?: string }>('/login', undefined, { method: 'POST', body: JSON.stringify({ email, password }) }); onLogin(result.access_token, { email, role: result.role ?? role }) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }; return <div className="auth"><div className="auth-copy"><div className="brand"><span>✦</span> SignalUnderwrite</div><h1>Decisions made<br />with clarity.</h1><p>A focused workspace for modern insurance underwriting.</p></div><form className="auth-card" onSubmit={submit}><p className="eyebrow">WELCOME</p><h2>{register ? 'Create your account' : 'Sign in to your workspace'}</h2>{error && <div className="notice">{error}</div>}<label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" required minLength={6} value={password} onChange={e => setPassword(e.target.value)} /></label>{register && <label>Role<select value={role} onChange={e => setRole(e.target.value)}><option>BROKER</option><option>UNDERWRITER</option><option>ADMIN</option></select></label>}<button className="primary" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button><button type="button" className="link" onClick={() => setRegister(!register)}>{register ? 'Already registered? Sign in' : 'Need an account? Register'}</button></form></div> }
function SubmissionForm({ token, onCreated }: { token: string; onCreated: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(''); try { await request('/create', token, { method: 'POST', body: JSON.stringify({ submission_type: f.get('type'), submission_summary: f.get('summary') || null, submission_details: { insured_firstname: f.get('first'), insured_lastname: f.get('last'), insured_age: Number(f.get('age')), insured_code: Number(f.get('code')), insured_email_address: f.get('email'), insured_address_1: f.get('address') || null, insured_city: f.get('city') || null } }) }); onCreated() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }; return <form className="panel form" onSubmit={submit}>{error && <div className="notice">{error}</div>}<h2>Applicant details</h2><div className="grid"><Field label="First name" name="first" /><Field label="Last name" name="last" /><Field label="Email" name="email" type="email" /><Field label="Age" name="age" type="number" /><Field label="Insured code" name="code" type="number" /><label>Submission type<select name="type"><option>PERSONAL</option><option>COMMERCIAL</option><option>LIFE</option></select></label><Field label="Address" name="address" /><Field label="City" name="city" /></div><label>Underwriter notes<textarea name="summary" placeholder="Optional context for the submission" /></label><button className="primary" disabled={busy}>{busy ? 'Running risk analysis…' : 'Create submission'}</button></form> }
function Field({ label, name, type = 'text' }: { label: string; name: string; type?: string }) { return <label>{label}<input name={name} type={type} required={['first', 'last', 'email', 'age', 'code'].includes(name)} /></label> }
function Metric({ title, value }: { title: string; value: number }) { return <div className="metric"><span>{title}</span><strong>{value}</strong></div> }
function AnalysisModal({ analysis, onClose }: { analysis: Analysis; onClose: () => void }) { let factors: string[]; try { factors = JSON.parse(analysis.risk_factors) } catch { factors = [analysis.risk_factors] } return <div className="modal-bg"><article className="modal"><button className="close" onClick={onClose}>×</button><p className="eyebrow">AI RISK ASSESSMENT</p><h2>{analysis.risk_level} risk <span>{analysis.risk_score}/100</span></h2><p>{analysis.risk_summary}</p><h3>Recommendation</h3><span className="status manual_review">{analysis.recommendation}</span><h3>Risk factors</h3><ul>{factors.map(f => <li key={f}>{f}</li>)}</ul>{analysis.missing_information && <><h3>Missing information</h3><p>{analysis.missing_information}</p></>}</article></div> }
